name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./shattered-pixel-dungeon-master-2
      
    - name: Build with Gradle
      run: ./gradlew    assembleDebug
      working-directory: ./shattered-pixel-dungeon-master-2
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: '**/*.apk'
      
